# Generated by Django 3.0.6 on 2020-05-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
