# Generated by Django 3.0.6 on 2020-05-16 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_event_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
