# Generated by Django 3.0.6 on 2020-05-17 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.UUIDField(default=uuid.UUID('dd285163-969d-45e0-bc14-72b9f7470045'), editable=False),
        ),
    ]
